# Access module outputs

# --- Return-path outputs (IAM resources created from access_requests) ---

output "iam_role_arns" {
  description = "IAM role ARNs keyed by module-purpose (return path to consuming modules)"
  value = {
    for key, role in aws_iam_role.requested :
    key => role.arn
  }
}

output "iam_role_names" {
  description = "IAM role names keyed by module-purpose (return path to consuming modules)"
  value = {
    for key, role in aws_iam_role.requested :
    key => role.name
  }
}

output "instance_profile_names" {
  description = "Instance profile names keyed by module-purpose (return path to consuming modules)"
  value = {
    for key, profile in aws_iam_instance_profile.requested :
    key => profile.name
  }
}

output "instance_profile_arns" {
  description = "Instance profile ARNs keyed by module-purpose (return path to consuming modules)"
  value = {
    for key, profile in aws_iam_instance_profile.requested :
    key => profile.arn
  }
}

# --- Report outputs ---

output "bucket_requests" {
  description = "S3 bucket request for access report storage (dependency inversion to storage module)"
  value = [
    {
      purpose            = "access-report"
      description        = "Access control reports generated by the access module"
      versioning_enabled = true
      lifecycle_days     = 365
      access_logging     = false
      # Upload is handled at the root level (not here) to avoid a validation-phase cycle:
      # bucket_requests.upload_trigger = local_file.access_report.id
      # -> access_requests -> archbot policies -> storage.bucket_arns -> bucket_requests
    }
  ]
}

output "report_ready" {
  description = "Opaque dependency handle - changes whenever the access report is rewritten. Pass to null_resource triggers to guarantee the file exists before use."
  value       = null_resource.access_report.id
}

output "artifact_requests" {
  description = "Artifact registry entry for the access control report (dependency inversion to portal)"
  value = [
    {
      name       = "access-report"
      version    = data.external.git_info.result.sha
      type       = "archive"
      path       = local.report_path
      source     = "access"
      created_at = data.external.git_info.result.timestamp
      url        = var.aws_region != "" ? "https://s3.console.aws.amazon.com/s3/object/${local.report_bucket_name}?region=${var.aws_region}&prefix=${local.report_s3_key}" : ""
    }
  ]
}

output "report_path" {
  description = "Local filesystem path to the generated JSON access report"
  value       = local.report_path
}

output "access_summary" {
  description = "Summary of access control policies by module"
  value = {
    iam_roles         = local.total_iam_roles
    security_groups   = local.total_security_groups
    resource_policies = local.total_resource_policies
    by_module         = local.summary_by_module
  }
}
