# Hybrid Activation Resources for Non-AWS Machines
# Extends configuration-management module to support WSL, on-premises servers, and other non-AWS machines
# via AWS Systems Manager hybrid activations

locals {
  # Extract hybrid activation config from state fragment
  hybrid_activations_enabled = length(var.config.hybrid_activations) > 0
  hybrid_activations         = var.config.hybrid_activations
}

# Hybrid Activation Resource
# Creates activation credentials for registering non-AWS machines with SSM
# Registration command: sudo /tmp/ssm/ssm-setup-cli -register -activation-code "<code>" -activation-id "<id>" -region "<region>"
resource "aws_ssm_activation" "activation" {
  for_each = local.hybrid_activations

  # Namespace isolation: activation name includes namespace to prevent conflicts
  name        = "${each.key}-${var.namespace}"
  description = each.value.description

  # IAM role for registered instances (created in iam.tf)
  iam_role = var.access_iam_role_names["configuration-management-hybrid-instance"]

  # Registration limits and expiration
  registration_limit = each.value.registration_limit
  expiration_date    = timeadd(timestamp(), "${each.value.expiration_days * 24}h")

  # Tags: Namespace included for isolation, Class tag for consistency with compute module
  # Provider default_tags automatically applied (Namespace, ManagedBy, etc.)
  # Note: Instance names auto-generated by SSM during registration with prefix from activation name
  tags = {
    Name  = "${each.key}-${var.namespace}"
    Class = each.key # Same pattern as compute instances (Class = instance class)
  }

  # Prevent drift on re-apply (expiration_date uses timestamp())
  lifecycle {
    ignore_changes = [expiration_date]
  }
}
